# Generated by Django 3.2.6 on 2021-08-19 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210818_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userlevel'),
        ),
    ]
